In [2]:
import numpy as np

arr1= np.zeros((2,5))
print(arr1)
print(arr1.dtype)
arr1

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
float64


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [3]:
arr2= np.zeros_like(arr1) #创建一个完全相同的
arr2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
arr3= np.ones((3,4))
arr3

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
arr4 = np.empty((3,7))
arr4

array([[2.37151510e-322, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        1.03977794e-312, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000]])

In [6]:
arr5=np.empty_like(arr4)
arr5

array([[2.37151510e-322, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        1.03977794e-312, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000]])