In [1]:
import numpy as np

arr1 =np.full((2,3),10)  #指定二维三列都是10
arr1

array([[10, 10, 10],
       [10, 10, 10]])

In [2]:
arr2 = np.full_like(arr1,1)
arr2

array([[1, 1, 1],
       [1, 1, 1]])

In [3]:
arr3= np.arange(0,10,2)  #从a到b每隔c个，包前不包后
arr3

array([0, 2, 4, 6, 8])

In [5]:
# 等差数列
# 分成c份 默认包含start和stop，如希望不包含，写endpoint=False
arr1= np. linspace(start=0,stop=10,num=7)
arr1

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

In [7]:
a1= np.linspace(0,10,3, endpoint=False)
a1

array([0.        , 3.33333333, 6.66666667])

In [10]:
#等比数列
#2为底，在2-5中间平均取4个数做指数运算
a3 =np.logspace(start=2,stop=5,num=4,base=2)
a3

array([ 4.,  8., 16., 32.])