ndarray生成随机元素数组

In [1]:
import numpy as np

arr1 = np.random.rand(2,3)
arr1

array([[0.23796417, 0.17700371, 0.21203646],
       [0.84797387, 0.89709564, 0.2240199 ]])

In [3]:
arr2 = np.random.randint(0,10,(2,3)) #随机生成0-10之间的元素，2行3列
arr2

array([[1, 8, 6],
       [0, 2, 8]], dtype=int32)

In [4]:
arr3= np.random.uniform(0,10,(3,3))
arr3

array([[0.1072199 , 5.34319797, 2.50041566],
       [5.48813366, 4.30276954, 3.42673263],
       [1.63255148, 0.93894899, 3.1820964 ]])

In [5]:
arr4 =np.random.randn(2,3)
arr4

array([[ 0.49253098, -0.83376077,  0.87377124],
       [ 0.67061131,  0.54730166,  0.34522816]])

In [6]:
m1 =np.matrix([[1,2],[3,4]])
print(m1)
print(type(m1))

[[1 2]
 [3 4]]
<class 'numpy.matrix'>
