In [1]:
import numpy as np

a1= np.array([[1,2,3],[4,3,6],[7,2,9]])
print(np.unique(a1))

[1 2 3 4 6 7 9]


In [3]:
arr1 = np.array([[1,2,3],[4,3,6]])
arr2 = np.array([[4,3,6],[7,2,9]])
print(arr1 +arr2)
print(arr1 * arr2)
print(arr1 / arr2)

[[ 5  5  9]
 [11  5 15]]
[[ 4  6 18]
 [28  6 54]]
[[0.25       0.66666667 0.5       ]
 [0.57142857 1.5        0.66666667]]


广播计算，数组中每个元素对标量计算

In [4]:
print(arr1 - 100)

[[-99 -98 -97]
 [-96 -97 -94]]
