In [4]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, TargetEncoder
import numpy as np

## 标签编码

In [3]:
data = ['bachelor','master','doctor','bachelor']

encoder = LabelEncoder()
data = encoder.fit_transform(data)
print(data)

[0 2 1 0]


## 独热编码

In [6]:
X = np.array([['red'],['blue'],['yellow'],['green']])
encoder= OneHotEncoder()
X = encoder.fit_transform(X).toarray()
print(X)

[[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]]


## 目标编码

In [11]:
x = np.array([['dog']*20+['cat']*20+['snake']*20]).T
y = np.array([90.3]*40+[80.1]*15+[21.1]*5)

In [12]:
encoder = TargetEncoder()
x = encoder.fit_transform(x, y)
print(x)

[[90.3       ]
 [90.3       ]
 [90.3       ]
 [90.3       ]
 [90.3       ]
 [90.3       ]
 [90.3       ]
 [90.3       ]
 [90.3       ]
 [90.3       ]
 [90.3       ]
 [90.3       ]
 [90.3       ]
 [90.3       ]
 [90.3       ]
 [90.3       ]
 [90.3       ]
 [90.3       ]
 [90.3       ]
 [90.3       ]
 [90.3       ]
 [90.3       ]
 [90.3       ]
 [90.3       ]
 [90.3       ]
 [90.3       ]
 [90.3       ]
 [90.3       ]
 [90.3       ]
 [90.3       ]
 [90.3       ]
 [90.3       ]
 [90.3       ]
 [90.3       ]
 [90.3       ]
 [90.3       ]
 [90.3       ]
 [90.3       ]
 [90.3       ]
 [90.3       ]
 [63.52832129]
 [66.37640694]
 [65.61953835]
 [65.61953835]
 [68.24918537]
 [65.61953835]
 [66.37640694]
 [66.37640694]
 [63.52832129]
 [65.61953835]
 [70.98235462]
 [63.52832129]
 [66.37640694]
 [65.61953835]
 [63.52832129]
 [70.98235462]
 [65.61953835]
 [68.24918537]
 [70.98235462]
 [66.37640694]]
