In [1]:
import torch
import torch.nn as nn

In [3]:
linear = nn.Linear(in_features=2,out_features=3)

In [4]:
print(linear.weight)
print(linear.bias)

Parameter containing:
tensor([[ 0.1573,  0.5660],
        [-0.6715, -0.2321],
        [-0.2314,  0.1120]], requires_grad=True)
Parameter containing:
tensor([0.3353, 0.2795, 0.0909], requires_grad=True)


## 向前传播

In [5]:
input = torch.tensor([10,20]).float()

In [6]:
out = linear.forward(input)
print(out)

tensor([ 13.2275, -11.0767,   0.0162], grad_fn=<ViewBackward0>)


In [8]:
# 构造数据：多条
input = torch.tensor([[10,20],[100,200]]).float()
out = linear.forward(input)
print(out)

tensor([[ 1.3227e+01, -1.1077e+01,  1.6176e-02],
        [ 1.2926e+02, -1.1328e+02, -6.5610e-01]], grad_fn=<AddmmBackward0>)
