In [6]:
import torch
from torch.utils.data import Dataset,TensorDataset

## 自定义数据集

In [2]:
class MyDataset(Dataset):
    def __init__(self,data):# 初始化
        self.data = data
    def __len__(self): # 获取数据集大小
        return len(self.data)
    def __getitem__(self, idx): # 返回索引号单条数据（告诉外界第n条数据有什么）
        return self.data[idx]

In [4]:
ds = MyDataset([10,20,30,40,50]) # 利用数据列表创建数据集

print(ds[0])
print(len(ds))

10
5


## 内置数据集（Tensor数据集）

In [7]:
tds= TensorDataset(torch.randn(10))
print(tds[0])
print(len(tds))


(tensor(-1.1751),)
10


## 数据加载器（DataLoader）

In [8]:
from torch.utils.data import DataLoader

In [9]:
x = torch.randn(10,3)
y = torch.randn(10)
tds = TensorDataset(x,y)

loader= DataLoader(tds,batch_size=3,shuffle=True, drop_last=False)

In [10]:
for input,target in loader:
    print(input,target)
    print("--------------")

tensor([[-0.4166, -0.6263,  0.2596],
        [ 0.7885, -1.5723,  0.9523],
        [ 1.0138,  0.8705,  1.0317]]) tensor([0.5425, 2.0899, 0.1388])
--------------
tensor([[-2.1579,  0.7314, -0.6156],
        [-1.6814,  0.8582, -1.1669],
        [ 0.0818, -0.2199, -0.5746]]) tensor([-0.0894, -0.8186,  0.4604])
--------------
tensor([[-0.2050, -1.0412, -1.2693],
        [ 0.3398,  0.3682, -1.2724],
        [ 0.9924,  0.1549, -0.3753]]) tensor([ 0.1757, -0.9800, -0.8112])
--------------
tensor([[-2.5243,  0.4596, -1.1371]]) tensor([-1.3235])
--------------
