In [19]:
import torch
import numpy as np

1.基于内容创建tensor

In [8]:
t1= torch.tensor([10,20,30])
print(t1)
print(t1.shape)

tensor([10, 20, 30])
torch.Size([3])


In [10]:
t1= torch.tensor([[10,20,30],[40,50,60]])
print(t1)
print(t1.shape)

tensor([[10, 20, 30],
        [40, 50, 60]])
torch.Size([2, 3])


In [11]:
t1= torch.tensor([[[10,20,30],[40,50,60]],[[10,20,30],[40,50,60]]])
print(t1)
print(t1.shape)

tensor([[[10, 20, 30],
         [40, 50, 60]],

        [[10, 20, 30],
         [40, 50, 60]]])
torch.Size([2, 2, 3])


In [15]:
t1= torch.tensor(np.array([[10,20,30],[40,50,60]]))
print(t1)
print(t1.shape)
print(t1.dtype)

tensor([[10, 20, 30],
        [40, 50, 60]])
torch.Size([2, 3])
torch.int64


## 2.基于形状创建

In [14]:
t1 =torch.Tensor(2,3,5)
print(t1)
print(t1.shape)
print(t1.dtype)

tensor([[[-3.6156e+21,  8.1556e-43,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]]])
torch.Size([2, 3, 5])
torch.float32


## 3.创建指定类型的张量

In [16]:
t1 = torch.tensor([[10,20,30],[40,50,60]],dtype=torch.float32)

print(t1.dtype)

torch.float32


In [20]:
t1 = torch.IntTensor(2,3)
print(t1.dtype)

torch.int32


In [22]:
t1= torch.LongTensor(2,3)
print(t1.dtype)

torch.int64


In [23]:
t1= torch.FloatTensor([10,20,30])
print(t1.dtype)

torch.float32


In [24]:
t1= torch.HalfTensor([10,20,30])
print(t1.dtype)

torch.float16


 ## 4.指定区间创建

In [26]:
t1 =torch.arange(10)
print(t1)

t1= torch.arange(start=0,end=10,step=2)
print(t1)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 2, 4, 6, 8])


In [27]:
t1= torch.linspace(1,10,3)
# 首和尾还有输出个数
print(t1)

tensor([ 1.0000,  5.5000, 10.0000])


In [28]:
t1=torch.logspace(1,3,3)
print(t1)

tensor([  10.,  100., 1000.])


## 5.根据填充创建

In [29]:
t1= torch.ones(2,3)
print(t1)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [30]:
t1 = torch.zeros(2,3)
print(t1)
t2 = torch.zeros_like(t1)
print(t2)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [31]:
t1 = torch.full((2,3),5)
print(t1)

tensor([[5, 5, 5],
        [5, 5, 5]])


In [32]:
t1 = torch.eye(5,4) #单位矩阵
print(t1)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [0., 0., 0., 0.]])


## 6.随机创建张量

In [ ]:
t1= torch.rand(2,3)# 均匀分布：【0，1】
print(t1)

In [34]:
t1 =torch.randint(low=10,high=100,size=(2,3)) # 均匀分布
print(t1)

tensor([[32, 81, 91],
        [98, 22, 67]])


In [35]:
t1= torch.randn(2,3) # 标准正态分布
print(t1)

tensor([[ 0.3391, -0.8331,  0.8950],
        [-0.3444, -0.6448,  0.6089]])


In [38]:
t1 = torch.normal(mean= 5,std= 1,size= (2,3)) # 均值是5，标准差为1，二行三列的张量
print(t1)

tensor([[6.7167, 4.5002, 3.9791],
        [5.0679, 6.4471, 6.2914]])


In [40]:
t1 = torch.randperm(10)  # 打乱
print(t1)

tensor([7, 3, 8, 9, 2, 6, 5, 1, 0, 4])
