In [2]:
import torch

In [3]:
t1 = torch.tensor([1, 2, 3])
print(t1.dtype)

torch.int64


In [4]:
t2=t1.type(torch.float)
print(t2.dtype)

torch.float32


In [5]:
t2 =t1.to(torch.float)
print(t2.dtype)

torch.float32


In [6]:
t2 =t1.float()
print(t2.dtype)

torch.float32


In [7]:
import numpy as np
t1 = torch.tensor([1, 2, 3])

In [8]:
n1 = t1.numpy()
print(type(n1))
print(n1)

<class 'numpy.ndarray'>
[1 2 3]


## ndarray --->numpy

In [9]:
n1 =np.array([1, 2, 3])
t1 =torch.from_numpy(n1)
print(t1)

tensor([1, 2, 3])


In [10]:
n1[0]=100
print(n1)
print(t2)

[100   2   3]
tensor([1., 2., 3.])


## 张量--->标量

In [12]:
t1 = torch.tensor([10]) #只有一个元素时，维度是什么都行
print(t1.item())

10
