In [1]:
import torch

In [3]:
t1 = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])

In [4]:
print(t1+10)
print(t1)
t1.add_(10)
print(t1)

tensor([[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]])


## 2.元素级运算

In [5]:
t1 = torch.tensor([[1,2,3],[4,5,6]])
t2 = torch.tensor([[7,8,9],[4,5,6]])

In [6]:
print(t1+t2) # 相加，形状一样，或者满足广播条件

tensor([[ 8, 10, 12],
        [ 8, 10, 12]])


In [7]:
t3 = torch.tensor([[9],[6]])
print(t1+t3)

tensor([[10, 11, 12],
        [10, 11, 12]])


In [8]:
print(t1 * t2)  # 哈德马积

tensor([[ 7, 16, 27],
        [16, 25, 36]])


## 3.矩阵相乘

In [11]:
t1 = torch.tensor([[1,2,3],[4,5,6]])
t2 = torch.tensor([[8,9],[4,5],[7,9]])

print(t1 @ t2)
print(t1.mm(t2)) # 必须是矩阵

tensor([[ 37,  46],
        [ 94, 115]])
tensor([[ 37,  46],
        [ 94, 115]])


In [19]:
t1= torch.tensor([[[1,2,3],[4,5,6],[6,5,4]],[[3,2,1],[3,2,1],[3,2,1]]])
t2 =torch.tensor([[[1,2],[3,4],[5,6]],[[6,5],[4,3],[2,1]]])
print(t1.shape,t2.shape)

torch.Size([2, 3, 3]) torch.Size([2, 3, 2])


In [20]:
print(t1@ t2)

tensor([[[22, 28],
         [49, 64],
         [41, 56]],

        [[28, 22],
         [28, 22],
         [28, 22]]])
