In [1]:
import torch

In [13]:
t1 = torch.randint (1,10,(2,3,4)).float()
print(t1)

tensor([[[6., 5., 4., 5.],
         [3., 4., 3., 4.],
         [3., 1., 6., 8.]],

        [[2., 1., 9., 6.],
         [8., 9., 2., 6.],
         [7., 9., 3., 7.]]])


In [5]:
print(t1.sum())

tensor(114)


In [6]:
t1.sum(dim=0)  #消维度：矩阵同位置相加

tensor([[ 7,  5, 11,  8],
        [14,  8, 10,  4],
        [12, 13, 11, 11]])

In [8]:
print(t1.sum(dim=1)) #每个矩阵变成一行

tensor([[12, 16, 10, 13],
        [21, 10, 22, 10]])


In [9]:
print(t1.sum(dim=2)) #每个矩阵横向相加

tensor([[16, 20, 15],
        [15, 16, 32]])


In [14]:
print(t1.mean(dim=0))

tensor([[4.0000, 3.0000, 6.5000, 5.5000],
        [5.5000, 6.5000, 2.5000, 5.0000],
        [5.0000, 5.0000, 4.5000, 7.5000]])


In [ ]:
print