In [1]:
import torch
t= torch.randint(0,10,(2,5,4))
print(t)

tensor([[[7, 3, 3, 5],
         [3, 6, 3, 3],
         [1, 4, 9, 3],
         [0, 4, 7, 7],
         [5, 6, 7, 6]],

        [[3, 7, 9, 9],
         [8, 2, 5, 1],
         [3, 7, 8, 9],
         [2, 1, 6, 9],
         [9, 3, 7, 7]]])


## 1.简单索引

In [3]:
print(t[0][0][0])
print(t[0,0,0])

tensor(7)
tensor(7)


In [4]:
print(t[0])

tensor([[7, 3, 3, 5],
        [3, 6, 3, 3],
        [1, 4, 9, 3],
        [0, 4, 7, 7],
        [5, 6, 7, 6]])


In [5]:
print(t[0,0])

tensor([7, 3, 3, 5])


## 2.范围索引

In [6]:
print(t[1:])

tensor([[[3, 7, 9, 9],
         [8, 2, 5, 1],
         [3, 7, 8, 9],
         [2, 1, 6, 9],
         [9, 3, 7, 7]]])


In [7]:
print(t[1,1:,2:])

tensor([[5, 1],
        [8, 9],
        [6, 9],
        [7, 7]])


## 3。列表索引,

In [8]:
list1 =[0,1,1] # 定位第几个矩阵
list2 =[1,3,2] # 定位第几行
# 上下一一对应
print(t[list1,list2])

tensor([[3, 6, 3, 3],
        [2, 1, 6, 9],
        [3, 7, 8, 9]])


In [9]:
list1 =[[0],[1]]
list2 =[1,3,2]
# 上面一个取下面所有
print(t[list1,list2])

tensor([[[3, 6, 3, 3],
         [0, 4, 7, 7],
         [1, 4, 9, 3]],

        [[8, 2, 5, 1],
         [2, 1, 6, 9],
         [3, 7, 8, 9]]])


## 4.布尔索引

In [11]:
mask = t >5
mask

tensor([[[ True, False, False, False],
         [False,  True, False, False],
         [False, False,  True, False],
         [False, False,  True,  True],
         [False,  True,  True,  True]],

        [[False,  True,  True,  True],
         [ True, False, False, False],
         [False,  True,  True,  True],
         [False, False,  True,  True],
         [ True, False,  True,  True]]])

In [12]:
print(t[mask])

tensor([7, 6, 9, 7, 7, 6, 7, 6, 7, 9, 9, 8, 7, 8, 9, 6, 9, 9, 7, 7])


In [13]:
# 取出每行首字母大于5的行
# 先筛选
mask = t[:,:,0]>5
print(mask)
# 再取出
print(t[mask])

tensor([[ True, False, False, False, False],
        [False,  True, False, False,  True]])
tensor([[7, 3, 3, 5],
        [8, 2, 5, 1],
        [9, 3, 7, 7]])


In [14]:
# 取出每列的首元素大于5的那些列
mask = t[:,0,:]<5
print(mask)

tensor([[False,  True,  True, False],
        [ True, False, False, False]])


In [17]:
print(t.mT[mask].T)

tensor([[3, 3, 3],
        [6, 3, 8],
        [4, 9, 3],
        [4, 7, 2],
        [6, 7, 9]])
