In [1]:
import torch
t= torch.randint(0,10,(2,5,4))
print(t)

tensor([[[2, 3, 0, 3],
         [3, 2, 8, 9],
         [6, 8, 2, 0],
         [1, 0, 3, 3],
         [4, 9, 1, 1]],

        [[6, 0, 3, 4],
         [9, 1, 3, 5],
         [5, 6, 2, 5],
         [3, 9, 1, 3],
         [3, 7, 2, 8]]])


## 维度变换

In [2]:
print(t.T)# (0,2,3) =>(3,2,0)


tensor([[[2, 6],
         [3, 9],
         [6, 5],
         [1, 3],
         [4, 3]],

        [[3, 0],
         [2, 1],
         [8, 6],
         [0, 9],
         [9, 7]],

        [[0, 3],
         [8, 3],
         [2, 2],
         [3, 1],
         [1, 2]],

        [[3, 4],
         [9, 5],
         [0, 5],
         [3, 3],
         [1, 8]]])


In [3]:
print(t.mT) # 只转置最后两个维度

tensor([[[2, 3, 6, 1, 4],
         [3, 2, 8, 0, 9],
         [0, 8, 2, 3, 1],
         [3, 9, 0, 3, 1]],

        [[6, 9, 5, 3, 3],
         [0, 1, 6, 9, 7],
         [3, 3, 2, 1, 2],
         [4, 5, 5, 3, 8]]])


In [4]:
print(t.transpose(0,1))
# 指定交换两个维度

tensor([[[2, 3, 0, 3],
         [6, 0, 3, 4]],

        [[3, 2, 8, 9],
         [9, 1, 3, 5]],

        [[6, 8, 2, 0],
         [5, 6, 2, 5]],

        [[1, 0, 3, 3],
         [3, 9, 1, 3]],

        [[4, 9, 1, 1],
         [3, 7, 2, 8]]])


In [5]:
print(t.permute(0,2,1))
print(t.permute(2,0,1).shape)

tensor([[[2, 3, 6, 1, 4],
         [3, 2, 8, 0, 9],
         [0, 8, 2, 3, 1],
         [3, 9, 0, 3, 1]],

        [[6, 9, 5, 3, 3],
         [0, 1, 6, 9, 7],
         [3, 3, 2, 1, 2],
         [4, 5, 5, 3, 8]]])
torch.Size([4, 2, 5])


## 形状调整

In [9]:
t1= t.reshape(-1)
print(t1)
print(t1.shape)

tensor([2, 3, 0, 3, 3, 2, 8, 9, 6, 8, 2, 0, 1, 0, 3, 3, 4, 9, 1, 1, 6, 0, 3, 4,
        9, 1, 3, 5, 5, 6, 2, 5, 3, 9, 1, 3, 3, 7, 2, 8])
torch.Size([40])


## 增删维度

In [10]:
t1 = torch.randint(1,10,(2,4))
print(t1)
print(t1.reshape(2,1,4))


tensor([[3, 2, 2, 8],
        [2, 8, 8, 7]])
tensor([[[3, 2, 2, 8]],

        [[2, 8, 8, 7]]])


In [11]:
print (t1.unsqueeze(dim=0))

tensor([[[3, 2, 2, 8],
         [2, 8, 8, 7]]])


# tensor的拼接

In [13]:
t1 =torch.randint(1,10,(2,1,3))
t2 = torch.randint(1,10,(2,3,3))
print(t1)
print(t2)

tensor([[[4, 7, 6]],

        [[6, 3, 1]]])
tensor([[[4, 2, 5],
         [2, 7, 3],
         [5, 6, 3]],

        [[9, 7, 3],
         [9, 1, 6],
         [7, 1, 9]]])


In [14]:
torch.cat((t1,t2),dim=1)

tensor([[[4, 7, 6],
         [4, 2, 5],
         [2, 7, 3],
         [5, 6, 3]],

        [[6, 3, 1],
         [9, 7, 3],
         [9, 1, 6],
         [7, 1, 9]]])