## 构建RNN层

In [4]:
import torch
import torch.nn as nn
from torch.onnx.symbolic_opset11 import index_put

In [6]:
rnn= nn. RNN(
    input_size=3,
    hidden_size=4,
    num_layers=3,
    bidirectional=True,
    batch_first=True,
)

# 向前传播

## 单层单向RNN

In [7]:
# 输入数据：(N,L,M) batch个数，句子长度，输入大小
input = torch.randn(2, 4,3)

In [8]:
rnn1 = nn.RNN(3, 4, batch_first=True)

In [15]:
output, hn = rnn1(input)

In [16]:
print(output.shape)
print(hn.shape)

torch.Size([2, 4, 4])
torch.Size([1, 2, 4])


In [17]:
print(output)

tensor([[[ 0.1754,  0.6486, -0.3736, -0.0593],
         [ 0.5614,  0.7835,  0.0151,  0.1217],
         [ 0.5647,  0.7683,  0.4604,  0.6328],
         [ 0.1342,  0.8223,  0.0794,  0.2596]],

        [[-0.0278,  0.4486, -0.1907, -0.2648],
         [ 0.2709,  0.8022, -0.7640, -0.6412],
         [ 0.7946,  0.8380, -0.0756,  0.1847],
         [ 0.5361,  0.9061, -0.2138,  0.0672]]], grad_fn=<TransposeBackward1>)


In [18]:
print(hn)

tensor([[[ 0.1342,  0.8223,  0.0794,  0.2596],
         [ 0.5361,  0.9061, -0.2138,  0.0672]]], grad_fn=<StackBackward0>)


## 双层单项

In [19]:
rnn2 = nn.RNN(3, 4, num_layers=2, batch_first=True)

In [20]:
output, hn = rnn2(input)
print(output.shape)
print(hn.shape)
print(output)

torch.Size([2, 4, 4])
torch.Size([2, 2, 4])
tensor([[[-0.1624,  0.6597, -0.3243,  0.2152],
         [ 0.1616,  0.6421, -0.2343, -0.1270],
         [ 0.1643,  0.6166, -0.1456, -0.2628],
         [ 0.2818,  0.6838,  0.1109, -0.2329]],

        [[ 0.1971,  0.6524,  0.0543, -0.0815],
         [-0.2652,  0.6676, -0.4317, -0.1618],
         [-0.0627,  0.7284, -0.2300,  0.1698],
         [-0.0754,  0.6270, -0.2926, -0.2269]]], grad_fn=<TransposeBackward1>)


In [21]:
print(hn)

tensor([[[-0.3230,  0.5853, -0.9508,  0.9099],
         [ 0.4529,  0.8618, -0.8858,  0.5840]],

        [[ 0.2818,  0.6838,  0.1109, -0.2329],
         [-0.0754,  0.6270, -0.2926, -0.2269]]], grad_fn=<StackBackward0>)


## 单层双向RNN

In [22]:
rnn3 = nn.RNN(3, 4,bidirectional=True, batch_first=True)

In [25]:
output, hn = rnn3(input)
print(output.shape)
print(hn.shape)
print(output)

torch.Size([2, 4, 8])
torch.Size([2, 2, 4])
tensor([[[ 0.4735, -0.2379, -0.4684, -0.2061,  0.2681,  0.8680,  0.5030,
           0.0995],
         [ 0.5732,  0.4114,  0.0986, -0.5052,  0.4139, -0.0808,  0.8300,
          -0.6183],
         [ 0.9103,  0.1001,  0.3577, -0.0730,  0.6554,  0.9108,  0.8426,
           0.8324],
         [ 0.7768,  0.8805,  0.6185, -0.3112, -0.3373,  0.0300,  0.2068,
          -0.8073]],

        [[ 0.6604,  0.7942,  0.4944, -0.2975, -0.3102,  0.6427,  0.0690,
          -0.0545],
         [ 0.1028, -0.1399, -0.9048, -0.2482, -0.6091,  0.0084, -0.0499,
          -0.8992],
         [ 0.3766, -0.6876, -0.6724, -0.5101,  0.5921,  0.8111,  0.7618,
           0.5536],
         [ 0.2734,  0.1083, -0.7256, -0.0725, -0.0698,  0.6966,  0.4559,
          -0.3090]]], grad_fn=<TransposeBackward1>)


In [26]:
print(hn)

tensor([[[ 0.7768,  0.8805,  0.6185, -0.3112],
         [ 0.2734,  0.1083, -0.7256, -0.0725]],

        [[ 0.2681,  0.8680,  0.5030,  0.0995],
         [-0.3102,  0.6427,  0.0690, -0.0545]]], grad_fn=<StackBackward0>)
